
services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - /C/Dev/docker-volumes/mongo/db:/data/db
      - /C/Dev/docker-volumes/mongo/configdb:/data/configdb

  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - /C/Dev/docker-volumes/postgres:/var/lib/postgresql/data

  ollama:
      image: ollama/ollama:0.6.1
      container_name: ollama
      restart: unless-stopped
      ports:
        - "11434:11434"
      volumes:
        - /C/Dev/docker-volumes/ollama:/root/.ollama/models
        
  open-webui:
    image: ghcr.io/open-webui/open-webui:git-74da9c4-ollama
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - /C/Dev/docker-volumes/open-webui:/app/backend/data
