
services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - /C/Dev/docker-volumes/mongo/db:/data/db
      - /C/Dev/docker-volumes/mongo/configdb:/data/configdb

  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - /C/Dev/docker-volumes/postgres:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /C/Dev/docker-volumes/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch    

  ollama:
      image: ollama/ollama:0.6.1
      container_name: ollama
      restart: unless-stopped
      ports:
        - "11434:11434"
      volumes:
        - /C/Dev/docker-volumes/ollama:/root/.ollama/models
        
  open-webui:
    image: ghcr.io/open-webui/open-webui:git-74da9c4-ollama
    container_name: open-webui
    restart: unless-stopped
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    volumes:
      - /C/Dev/docker-volumes/open-webui:/app/backend/data
